</$objtype/mkfile

all = $home/lib/profile $home/lib/plumbing $home/lib/git $home/lib/bin /cfg/$sysname $objtype/bin/prompt

all:V: $all

clean:V:
	rm -rf $all

$home/lib/profile: profile
	cp $prereq $target

$home/lib/plumbing: plumbing
	cp $prereq $target

$home/lib/git: git
	rm -rf $target
	clone $prereq $target

$home/lib/themes: themes
	rm -rf $target
	clone $prereq $target

$home/lib/bin: bin
	rm -rf $target
	clone $prereq $target
	bind -qa $home/lib/bin /bin
	bind -qa $home/lib/bin/git /bin/git/

/cfg/$sysname: cfg/$sysname
	rm -rf $target
	clone $prereq $target

/$objtype/bin/prompt: prompt.$O
	$LD -o $target $prereq

%.$O: %.c
	$CC $CFLAGS src/$stem.c
