typeset -U path cdpath fpath manpath
autoload -U compinit && compinit
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.local/share/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY
setopt INTERACTIVE_COMMENTS
setopt PROMPT_SUBST

bindkey -e

PROMPT='$(prompt $?)'
PATH="$HOME/bin:$HOME/.local/zig:$HOME/.local/zls:$HOME/.local/janet/bin:$HOME/.local/fennel/bin::$PATH"

export EDITOR="$(which vis)"
export VISUAL=$EDITOR

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' list-suffixes zstyle ':completion:*' expand prefix suffix 

case $TERM in
  xterm*)
    precmd () {print -Pn "\e]0;%m:%~\a"}
    ;;
esac


# Aliases
alias cp='cp -i'
alias df='df -h'
alias l='exa'
alias ls='exa -l'
alias lsd='exa -al'
alias mv='mv -i'
alias rm='rm -i'
alias tree='exa --tree --git-ignore'
